version: '3.7'
services:
  backend:
    image: '${DOCKER_IMAGE_BACKEND_STAGING}:${DOCKER_TAG-latest}'
    build:
      context: ../
      dockerfile: packages/backend/Dockerfile
      args:
        BACKEND_ENV: staging
        PROTOCOL: ${PROTOCOL}
        DOMAIN: ${DOMAIN_STAGE}

  worker:
    image: '${DOCKER_IMAGE_WORKER_STAGING}:${DOCKER_TAG-latest}'
    build:
      context: ../
      dockerfile: packages/worker/Dockerfile
      args:
        BACKEND_ENV: staging
        PROTOCOL: ${PROTOCOL}
        DOMAIN: ${DOMAIN_STAGE}

  frontend:
    image: '${DOCKER_IMAGE_FRONTEND_STAGING}:${DOCKER_TAG-latest}'
    build:
      context: ../
      dockerfile: packages/frontend/Dockerfile
      args:
        VUE_APP_NAME: ${VUE_APP_NAME}
        VUE_APP_PROTOCOL: ${VUE_APP_PROTOCOL}
        VUE_APP_DOMAIN: ${DOMAIN_STAGE}
