version: '3.7'
services:

  backend:
    restart: "no"
    build:
      context: ../
      dockerfile: packages/backend/Dockerfile
      args:
        BACKEND_ENV: development
    command: ["yarn", "run", "start:backend:debug"]
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ../packages/backend:/app/packages/backend
      - ../packages/shared:/app/packages/shared
      - /app/packages/backend/node_modules/
      - /app/packages/shared/node_modules/
#      - /app/packages/backend/dist/

  frontend:
    restart: "no"
    build:
      context: ../
      dockerfile: packages/frontend/Dockerfile
      args:
        FRONTEND_ENV: development

  proxy:
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--api.debug=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=true"
      - "--entrypoints.web.address=:80"

  # MySql instance for testing purposes only (old data exploring)
  mysql:
    image: mysql:5.6
    container_name: mysql
    hostname: mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: labpad_new
      MYSQL_USER: admin
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
