version: '3.7'
services:
  backend:
    restart: always
    image: ${DOCKER_IMAGE_BACKEND}:${TAG-latest}
    ports:
      - 3000:3000
    command: ["yarn", "run", "start:backend:prod"]

  worker:
    restart: always
    image: ${DOCKER_IMAGE_WORKER}:${TAG-latest}
    command: ["yarn", "run", "start:worker:prod"]

  frontend:
    restart: always
    image: ${DOCKER_IMAGE_FRONTEND}:${TAG-latest}

  proxy:
    command:
      - "--log.level=INFO"
      - "--api.insecure=false"
      - "--api.debug=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
