version: '3.7'
services:
  backend:
    restart: "no"
    build:
      context: ../
      dockerfile: packages/backend/Dockerfile
      args:
        BACKEND_ENV: staging
    ports:
      - 3000:3000
    command: ["yarn", "run", "start:backend:prod"]

  worker:
    restart: "no"
    build:
      context: ../
      dockerfile: packages/worker/Dockerfile
      args:
        BACKEND_ENV: staging
    command: ["yarn", "run", "start:worker:prod"]

  frontend:
    restart: "no"
    build:
      context: ../
      dockerfile: packages/frontend/Dockerfile
      args:
        FRONTEND_ENV: staging

  proxy:
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--api.debug=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=true"
      - "--entrypoints.web.address=:80"
